version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: main
    assignees: ["josesolisrosales"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    allowed_updates:
      - match:
        update_type: "security"
    assignees: ["josesolisrosales"]

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: main
    allowed_updates:
      - match:
        update_type: "security"
    assignees: ["josesolisrosales"]